[tool.poetry]
name = "003_streamlit_split_and_summarize"
version = "1.0.0"
description = "App de Streamlit para resumir textos y PDFs"
authors = ["Tu Nombre <tu@email.com>"]
readme = "README.md"
# Se deshabilita la instalaciÃ³n como paquete
package-mode = false

[tool.poetry.dependencies]
python = "^3.11"
streamlit = "^1.51.0"
PyPDF2 = "^3.0.1"
openai = "^1.0.0"

[build-system]
requires = ["poetry-core>=1.3.0"]
build-backend = "poetry.core.masonry.api"
